# Generated by Django 3.1.7 on 2021-02-22 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_item_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://fitmirchi.com/admin/assets/images/image_not_available.png', max_length=500),
        ),
    ]
